### PR TITLE
Fix accidental reversal of colorized log messages

### PR DESCRIPTION
**Pull request by anguslees**
The mechanical process used to create #101 accidentally reversed the
order of log messages.  Oops.  This change restores the
correct (original) order.

Fixes PR #101

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by gyuho** [comment]
Can we also add this :)

```
--- a/ec2config/config.go
+++ b/ec2config/config.go
@@ -183,7 +183,7 @@ type Config struct {
 }

 func (c Config) Colorize(input string) string {
-       colorize := colorstring.Colorize{Disable: !c.LogColor, Reset: true}
+       colorize := colorstring.Colorize{Colors: colorstring.DefaultColors, Disable: !c.LogColor, Reset: true}
        return colorize.Color(input)
 }
```

I see them printed plain color :0

**Comment by gyuho** [comment]
> Can we also add this :)
> 
> ```
> --- a/ec2config/config.go
> +++ b/ec2config/config.go
> @@ -183,7 +183,7 @@ type Config struct {
>  }
> 
>  func (c Config) Colorize(input string) string {
> -       colorize := colorstring.Colorize{Disable: !c.LogColor, Reset: true}
> +       colorize := colorstring.Colorize{Colors: colorstring.DefaultColors, Disable: !c.LogColor, Reset: true}
>         return colorize.Color(input)
>  }
> ```
> 
> I see them printed plain color :0

Let me add that after I merge this :)

**Comment by gyuho** [comment]
https://github.com/aws/aws-k8s-tester/commit/253757b7de02ccb20b0771c7a7cc452a2b8fa9fe

**Comment by anguslees** [comment]
Added.

**Pull request merged**
